# Site settings
title: "Cloud | DevOps Engineer"
description: "Dileep Kushwaha's Resume."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed
permalink: "/resume"
# Resume settings
resume_avatar:                  "true"
resume_name:                    "DIleep Kumar"
resume_title:                   "Cloud Engineer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "dileepkushwaha@hotmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "9870268640"
resume_contact_address:         "India"

resume_header_contact_info:     "742 Evergreen Terrace, Springfield • 555-7334 • lisasimpson@youremailaddress.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>Dedicated to optimize, experienced DevOps Engineer who understands the melding of operations and development to quickly deliver code to customers. Has experience with the Azure Cloud and monitoring as well as DevOps processes in Windows and Linux environment.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/dileepkushwaha"
  #resume_twitter_url:           "http://twitter.com/dileepkush"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/dileepkushwaha"
  # resume_instagram_url:         "insert your Instagram URL here"
  #resume_website_url:           "http://joelglovier.com"
  #resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
